print("Welcome to Github Repository.")
print ("roll no. 34 & 28","continue and break func.")
print("Roll No. 21,12, 'print prime numbers in an interval '")
print("Roll no."35,"sum of prime numbers")
print("Roll no. 24 & 26","for loop") 
print("roll no. 3 and 32, factorials")
print("roll no. 4 and 6;for swap")
print("roll no 5 and 17, prime no")
print("roll no, 15 : Area of circle")
print("roll no,38 : greater no")
