print("Welcome to Github Repository.")
print ("roll no. 34 & 28","continue and break func.")
print("Roll No. 21,12, 'print prime numbers in an interval '")
print("roll no.15,'area of circle' ")
print("roll no 04,06,swapping of nos")
