print("Welcome to Github Repository.")
print ("roll no. 34 & 28","continue and break func.")
print("Roll No. 21,12, 'print prime numbers in an interval '")
print("Roll number is 3 and 32, 'factorials.py'")
print("roll number is 08 and 02,'while loop'")
print("roll number is 15,'area of circle'")
print("roll number is 04and 06,'swapping'")
